name: Build/release

on: push

jobs:
  release:
    strategy:
      matrix:
        os:
          - macos
          - windows
        include:
          - os: macos
            runner: macos-latest
            artifact: ./out/make/zip/darwin/arm64/my-app-darwin-arm64-1.0.0.zip
          - os: windows
            runner: windows-latest
            artifact: ./out/make/zip/darwin/arm64/my-app-darwin-arm64-1.0.0.zip

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create release
        run: yarn make

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ matrix.os }}-${{ github.sha }}
          files: ${{ matrix.artifact }}
